INSERT INTO [VoteType](VotingType,VoteTypeDescription) VALUES ('Yes/No Poll','Voters will get to choose between two simple options: yes or no.');
INSERT INTO [VoteType](VotingType,VoteTypeDescription) VALUES ('Multiple Choice Poll','Voters will get to choose one option from up to 10 choices.');
INSERT INTO [VoteType](VotingType,VoteTypeDescription) VALUES ('Multiple Choice Multi-Round Poll','Voters will get to choose one option from up to 10 choices. There can be multiple rounds of voting until one option has the majority of votes');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Pacific Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Dateline Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('UTC-11');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Samoa Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Hawaiian Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Alaskan Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Pacific Standard Time (Mexico)');
INSERT INTO [VoteTimeZones](TimeName) VALUES('US Mountain Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Mountain Standard Time (Mexico)');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Mountain Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central America Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Standard Time (Mexico)');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Canada Central Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('SA Pacific Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Eastern Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('US Eastern Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Venezuela Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Paraguay Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Atlantic Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Brazilian Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('SA Western Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Pacific SA Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Newfoundland Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('E. South America Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Argentina Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('SA Eastern Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Greenland Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Montevideo Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('UTC-02');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Mid-Atlantic Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Azores Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Cape Verde Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Morocco Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('UTC');
INSERT INTO [VoteTimeZones](TimeName) VALUES('GMT Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Greenwich Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('W. Europe Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Europe Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Romance Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central European Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('W. Central Africa Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Namibia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Jordan Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('GTB Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Middle East Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Egypt Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Syria Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('South Africa Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('FLE Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Israel Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('E. Europe Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Arabic Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Arab Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Russian Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('E. Africa Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Iran Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Arabian Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Azerbaijan Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Mauritius Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Georgian Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Caucasus Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Afghanistan Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Ekaterinburg Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Pakistan Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('West Asia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('India Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Sri Lanka Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Nepal Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Asia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Bangladesh Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('N. Central Asia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Myanmar Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('SE Asia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('North Asia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('China Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('North Asia East Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Singapore Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('W. Australia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Taipei Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Ulaanbaatar Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Tokyo Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Korea Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Yakutsk Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Cen. Australia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('AUS Central Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('E. Australia Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('AUS Eastern Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('West Pacific Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Tasmania Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Vladivostok Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Central Pacific Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('New Zealand Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('UTC+12');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Fiji Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Kamchatka Standard Time');
INSERT INTO [VoteTimeZones](TimeName) VALUES('Tonga Standard Time');
